### ISSUE TITLE
Getting a KeyError

### ISSUE THREAD

**Issue by yelha** [marcan/pacemaker-exporter#2]
Hello!

I installed the requirements but for me the exporter is not working. I get the following:

> Traceback (most recent call last):
>   File "/usr/bin/prometheus-pacemaker-exporter.py", line 197, in <module>
>     REGISTRY.register(PacemakerCollector(args))
>   File "/usr/local/lib/python3.5/dist-packages/prometheus_client/core.py", line 50, in register
>     names = self._get_names(collector)
>   File "/usr/local/lib/python3.5/dist-packages/prometheus_client/core.py", line 86, in _get_names
>     for metric in desc_func():
>   File "/usr/bin/prometheus-pacemaker-exporter.py", line 94, in collect
>     float(attrib.attrib['expected']))
> KeyError: 'expected'

OS: Debian 9.3
Python: 3.5
prometheus-client: 0.1.1
Pacemaker: 1.1.16

As I do not know python I wanted to ask if you have an idea how to fix this.

Thanks!

**Comment by marcan** [comment]
This is probably caused by a different Pacemaker version not including the same data. Please post the output of  `crm_mon -X` so I can take a look.

You can also just comment out or remove lines 93/94 of the file, which will remove that metric, and see if everything else works.

**Comment by yelha** [comment]
Commenting the lines out did the trick! 

Thanks a lot and best regards!
